
name: opom.ca Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  opomca_Automated_Deployment_Process:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve actions/checkout@v2 💻
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Syncing development with prod environment Opom Canada
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd opomca
          rm -f package-lock.json
          rm -rf node_modules
          rm -rf ./miscellaneous/db/dump.txt
          chmod -R 755 models
          rm -rf ./models/*
          git fetch origin master
          git merge --strategy=recursive --strategy-option=theirs origin/master || echo "Merge failed, resolving manually"
          git add .
          git commit -m "Merge conflicts resolved (using 'theirs' strategy)" || echo "No conflicts to commit"
          git pull https://${{ secrets.GITHUUB_USERNAME }}:${{ secrets.GITHUUB_PASSWORD }}@github.com/${{ secrets.GITHUUB_USERNAME }}/earnanswers.git master --strategy=recursive --strategy-option=theirs
          npm install
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_USERPASSWORD }} ${{ secrets.DB_NAME }} < ./miscellaneous/db/dump.txt
          sequelize-auto -o \"./models\" -d ${{ secrets.DB_NAME }} -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USERNAME }} -p ${{ secrets.DB_PORT }} -x ${{ secrets.DB_USERPASSWORD }} -e mysql
          pm2 restart index